#!/usr/bin/env bash

export \
  ARCH=$(dpkg --print-architecture) \
  K8S_VERSION=${K8S_VERSION:-v1.33.2} \
  CRICTL_VERSION=${CRICTL_VERSION:-v1.33.0} \
  RUNC_VERSION=${RUNC_VERSION:-v1.3.0} \
  CNI_PLUGINS=${CNI_PLUGINS:-v1.7.1} \
  CONTAINERD_VERSION=${CONTAINERD_VERSION:-2.1.3} \
  ETCD_VERSION=${ETCD_VERSION:-v3.6.1} \
  NERDCTL_VERSION=${NERDCTL_VERSION:-2.1.3} \
  HELM_VERSION=${HELM_VERSION:-v3.18.4} \
  CLUSTER_DOMAIN=${CLUSTER_DOMAIN:-cluster.local} \
  COUNTRY="${COUNTRY:-DE}" \
  CITY="${CITY:-Bochum}" \
  STATE="${STATE:-NRW}"
