---
apiVersion: v1
kind: Service
metadata:
  name: buildkitd-headless
  namespace: buildkit
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: buildkit
  ports:
  - protocol: TCP
    port: 1234
    targetPort: 1234
