---
apiVersion: v1
kind: Service
metadata:
  name: buildkitd
  namespace: buildkit
spec:
  type: NodePort
  selector:
    app: buildkit
  ports:
  - protocol: TCP
    port: 1234
    targetPort: 1234
    nodePort: 31234
