name: Renovate

on:
  workflow_dispatch:
  schedule:
  - cron: '0 6 * * *' # Runs daily at 6:00 UTC

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Self-hosted Renovate
      uses: renovatebot/github-action@v43.0.4
      with:
        token: ${{ secrets.RENOVATE_TOKEN }}
        configurationFile: renovate.json
        env-regex: "^(?:RENOVATE_\\w+|LOG_LEVEL|GITHUB_COM_TOKEN|NODE_OPTIONS)$"
      env:
        LOG_LEVEL: 'debug'
