name: Renovate

on:
  workflow_dispatch:
  schedule:
  - cron: '0 6 * * *' # Runs daily at 6:00 UTC

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: renovatebot/github-action@v40.1.11
      with:
        token: ${{ secrets.RENOVATE_TOKEN }}
        configurationFile: renovate.json
